version: 0.2


        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
  pre_build:
    on-failure: ABORT
    commands:
      - sudo chmod 666 /var/run/docker.sock
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY
  build:
    on-failure: ABORT
    commands:
      - docker build -t $IMAGE .
      - docker tag $IMAGE:$IMAGE_TAG $REPOSITORY/$IMAGE:$IMAGE_TAG
  post_build:
    on-failure: ABORT
    commands:
      - docker images ls -a
      - docker push public.ecr.aws/j9q6e1n9/$IMAGE:$IMAGE_TAG
    
